[package]
name = "dns-over-https-proxy"
version = "0.1.0"
authors = ["Michael Farrell <micolous+git@gmail.com>"]

[dependencies]
reqwest = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
